name: Docker Image CI (vchaos-wyoming-piper)

on:
  push:
    branches: [ "main" ]
    paths:
      - Dockerfile
  pull_request:
    branches: [ "main" ]
    paths:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag vchaos-wyoming-piper:$(date +%s)